Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using cwagnerPortfolio.Helpers;
using cwagnerPortfolio.Models;
using Microsoft.AspNet.Identity;
using PagedList;
using PagedList.Mvc;

namespace cwagnerPortfolio.Controllers
{
    [RequireHttps]
    public class BlogController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Blog
        public ActionResult Index(int? page)
        {
            int pageSize = 3;
            int pageNumber = (page ?? 1);

            var posts = db.Posts.OrderByDescending(d => d.Created).AsQueryable();

            if (!User.IsInRole("Admin")) posts = posts.Where(p => p.Published);

            return View(posts.Include(i => i.Comments).ToPagedList(pageNumber, pageSize));
        }

        // POST: Search
        [HttpPost]
        public ActionResult Index(string searchStr, int? page)
        {
            int pageSize = 3;
            int pageNumber = (page ?? 1);

            ViewBag.Search = searchStr;
            SearchHelper search = new SearchHelper();
            var blogList = search.IndexSearch(searchStr);

            if (Request.IsAuthenticated && User.IsInRole("Admin"))
            {
                return View(blogList.ToPagedList(pageNumber, pageSize));
            }
            else
            {
                return View(blogList.Where(p => p.Published == true).ToPagedList(pageNumber, pageSize));
            }
        }

        // GET: Blog/Details/5
        public ActionResult Details(string Slug)
        {
            if (String.IsNullOrWhiteSpace(Slug))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Posts.FirstOrDefault(p => p.Slug == Slug);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // GET: Blog/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            if (User.IsInRole("Admin"))
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        // POST: Blog/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "Id,Title,Slug,Body,Created,Updated,MediaUrl,Published")] Blog blog, HttpPostedFileBase image)
        {
            if (image != null && image.ContentLength > 0)
            {
                var ext = Path.GetExtension(image.FileName).ToLower();
                if (ext != ".png" && ext != ".jpg" && ext != ".jpeg" && ext != ".gif" && ext != ".bmp")
                    ModelState.AddModelError("image", "Invalid Format.");
            }
            if (ModelState.IsValid)
            {
                if(image != null)
                {
                    var filePath = "/wwwroot/images/";
                    var absPath = Server.MapPath("~" + filePath);
                    blog.MediaUrl = filePath + image.FileName;
                    image.SaveAs(Path.Combine(absPath, image.FileName));
                }
                var Slug = StringUtilities.URLFriendly(blog.Title);
                if (String.IsNullOrWhiteSpace(Slug))
                {
                    ModelState.AddModelError("Title", "Invalid title");
                    return View(blog);
                }
                if (db.Posts.Any(p => p.Slug == Slug))
                {
                    ModelState.AddModelError("Title", "The title must be unique");
                    return View(blog);
                }

                blog.Slug = Slug;
                blog.Created = DateTimeOffset.Now;
                db.Posts.Add(blog);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(blog);
        }

        // GET: Blog/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (User.IsInRole("Admin"))
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Blog blog = db.Posts.Find(id);
                if (blog == null)
                {
                    return HttpNotFound();
                }
                return View(blog);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        // POST: Blog/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "Id,Title,Slug,Body,Created,Updated,MediaUrl,Published")] Blog blog, string mediaURL, HttpPostedFileBase image)
        {
            if (image != null && image.ContentLength > 0)
            {
                var ext = Path.GetExtension(image.FileName).ToLower();
                if (ext != ".png" && ext != ".jpg" && ext != ".jpeg" && ext != ".gif" && ext != ".bmp")
                {
                    ModelState.AddModelError("image", "Invalid Format.");
                }
            }
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    var filePath = "/wwwroot/images/";
                    var absPath = Server.MapPath("~" + filePath);
                    blog.MediaUrl = filePath + image.FileName;
                    image.SaveAs(Path.Combine(absPath, image.FileName));
                }
                else
                {
                    blog.MediaUrl = mediaURL;
                }

                blog.Updated = DateTimeOffset.Now;
                db.Entry(blog).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blog);
        }

        // GET: Blog/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Posts.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // POST: Blog/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Blog blog = db.Posts.Find(id);
            db.Posts.Remove(blog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace cwagnerPortfolio.Controllers
{
    [RequireHttps]
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using cwagnerPortfolio.Models;

namespace cwagnerPortfolio.Controllers
{
    [RequireHttps]
    public class FeedbackController : Controller
    {
        // GET: Feedback
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Contact(EmailModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var body = "<p>Email From: <bold>{0}</bold>" +
                        "({1})</p><p>Subject: </p><p>{2}</p><p>Message: </p><p>{3}</p><p>{4}</p>";
                    var from = "MyPortfolio<cwagner0604@gmail.com>";
                    var footNote = "This is a message from your portfolio site.  The name and the email of the contacting person is above.";
                    var email = new MailMessage(from, ConfigurationManager.AppSettings["emailto"])
                    {
                        Body = string.Format(body, model.FromName, model.FromEmail, model.Subject, model.Body, footNote),
                        IsBodyHtml = true
                    };
                    var svc = new PersonalEmail();
                    await svc.SendAsync(email);
                    return RedirectToAction("Sent");
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                    await Task.FromResult(0);
                }
            }
            return View(model);
        }

        //Message Sent
        public ActionResult Sent()
        {
            return View();
        }
    }
}

Controllers/ResumeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace cwagnerPortfolio.Controllers
{
    [RequireHttps]
    public class ResumeController : Controller
    {
        // GET: Resume
        public ActionResult Index()
        {
            return View();
        }
    }
}

Views/Shared/_JavascriptExerciseModal.cshtml
@model cwagnerPortfolio.Models.JsExerciseViewModel
@using cwagnerPortfolio.Helpers;

<div class="tab-pane active" id="1a">
    @Html.FileTextAsContent(Model.Intro)
</div>
<div class="tab-pane" id="2a">
    @Html.FileTextAsContent(Model.Html)
</div>
<div class="tab-pane" id="3a">
    <pre class="brush: js">
@Html.Encode(Html.FileTextAsContent(Model.Javascript))
    </pre>
</div>

<script>SyntaxHighlighter.highlight();</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<!--[if IE 9]>
<html class="ie9" lang="en">    <![endif]-->
<!--[if IE 8]>
<html class="ie8" lang="en">    <![endif]-->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name=viewport content="width=device-width, initial-scale=1">

    <title>Christina Wagner | Portfolio</title>

    <meta name="description" content="My personal portfolio site that includes links to projects and GitHub.">
    <meta name="keywords" content="html5, template, website, responsive, bootstrap">
    <meta name="author" content="neuethemes">

    <!-- Preloader -->
    <link href="/wwwroot/assets/custom/2.2.0/css/preloader.css" property='stylesheet' rel="stylesheet" type="text/css" media="screen" />

    <!-- CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" media="screen">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" property='stylesheet' rel="stylesheet" type="text/css" media="screen" />
    <link href="/wwwroot/assets/vendor/flaticons/flaticon.min.css?v=29022016" property='stylesheet' rel="stylesheet" type="text/css" media="screen" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <link href="/wwwroot/assets/vendor/hover/css/hover-min.css?v=2.0.2" property='stylesheet' rel="stylesheet" type="text/css" media="screen" />
    <link href="/wwwroot/assets/vendor/mfp/css/magnific-popup.min.css?v=1.1.0" property='stylesheet' rel="stylesheet" type="text/css" media="screen" />
    <link href="/wwwroot/assets/vendor/owl-carousel/assets/owl.carousel.min.css?v=2.1.0" property='stylesheet' rel="stylesheet" type="text/css" media="screen" />

    <!-- Custom styles -->
    <link href="/wwwroot/assets/custom/2.2.0/css/style.css" property='stylesheet' rel="stylesheet" type="text/css" media="screen" />
    <link href="/wwwroot/assets/custom/2.2.0/css/layouts/helena.css" property='stylesheet' rel="stylesheet" type="text/css" media="screen" />
    <link href="/wwwroot/assets/custom/2.2.0/css/colors/pastel.css" id="color-styles" property='stylesheet' rel="stylesheet" type="text/css" media="screen" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/pretty-checkbox/2.2.1/pretty.min.css" rel="stylesheet" />
    <!--Syntax Highlighter-->
    <link href="~/Content/SyntaxHighlighter/shCore.css" rel="stylesheet" />
    <link href="~/Content/SyntaxHighlighter/shCoreEclipse.css" rel="stylesheet" />
    <link href="~/Content/SyntaxHighlighter/shThemeEclipse.css" rel="stylesheet" />
    <link href="~/Content/PagedList.css" rel="stylesheet" />
</head>

<body id="helena" class="boxed">

    <!--Pre-Loader-->
    <div id="preloader"></div>

    <header>

        <section id="top-navigation" class="container-fluid nopadding">
            <div class="row nopadding ident ui-bg-color01">
                <!-- Photo -->
                <a href="index.html">
                    <div class="col-md-4 photo-03 vc-photo">&nbsp;</div>
                </a>
                <!-- /Photo -->
                <div class="col-md-8 vc-name nopadding">
                    <!-- Name-Position -->
                    <div class="row nopadding name">
                        <div class="col-md-10 name-title"><h1 class="font-accident-two-extralight">Christina Wagner</h1></div>
                        <div class="col-md-2 nopadding name-pdf">
                            <a href="https://github.com/christinawagner" class="hvr-sweep-to-right" target="_blank"><i class="fa fa-github fa-3x" title="View GitHub Repositories"></i></a>
                        </div>
                    </div>
                    <div class="row nopadding position">
                        <div class="col-md-10 position-title">

                            <section class="cd-intro">
                                <h2 class="cd-headline clip is-full-width font-accident-two-light">
                                    <span>The experienced </span>
                                    <span class="cd-words-wrapper">
                                        <b class="is-visible">Veterinary Nurse</b>
                                        <b>Developer</b>
                                        <b>Team Member</b>
                                    </span>
                                </h2>
                            </section>

                        </div>
                        <div class="col-md-2 nopadding pdf">
                            <a href="https://www.linkedin.com/in/christina-d-wagner" class="hvr-sweep-to-right" target="_blank"><i class="flaticon-linkedin22" title="My LinkedIn Profile"></i></a>
                        </div>
                    </div>
                    <!-- /Name-Position -->
                    <!-- Main Navigation -->

                    <ul id="nav" class="row nopadding cd-side-navigation">
                        <li class="col-xs-4 col-sm-2 nopadding menuitem ui-menu-color01" data-animation-duration="1000" data-animation-delay="100">
                            <a href="@Url.Action("Index", "Home")" class="hvr-sweep-to-bottom"><i class="flaticon-insignia"></i><span>home</span></a>
                        </li>
                        <li class="col-xs-4 col-sm-2 nopadding menuitem ui-menu-color02" data-animation-duration="1000" data-animation-delay="300">
                            <a href="@Url.Action("Index", "Resume")" class="hvr-sweep-to-bottom"><i class="flaticon-graduation9"></i><span>resume</span></a>
                        </li>
                        <li class="col-xs-4 col-sm-2 nopadding menuitem ui-menu-color03" data-animation-duration="1000" data-animation-delay="500">
                            <a href="@Url.Action("Index", "Portfolio")" class="hvr-sweep-to-bottom"><i class="flaticon-book-bag2"></i><span>portfolio</span></a>
                        </li>
                        <li class="col-xs-4 col-sm-2 nopadding menuitem ui-menu-color04" data-animation-duration="1000" data-animation-delay="700">
                            <a href="@Url.Action("Index", "Contact")" class="hvr-sweep-to-bottom"><i class="flaticon-placeholders4"></i><span>about</span></a>
                        </li>
                        <li class="col-xs-4 col-sm-2 nopadding menuitem ui-menu-color05" data-animation-duration="1000" data-animation-delay="900">
                            <a href="@Url.Action("Index", "Feedback")" class="hvr-sweep-to-bottom"><i class="flaticon-earphones18"></i><span>feedback</span></a>
                        </li>
                        <li class="col-xs-4 col-sm-2 nopadding menuitem ui-menu-color06" data-animation-duration="1000" data-animation-delay="1100">
                            <a href="@Url.Action("Index", "Blog")" class="hvr-sweep-to-bottom"><i class="flaticon-pens15"></i><span>blog</span></a>
                        </li>
                    </ul>

                    <!-- /Main Navigation -->

                </div>
            </div>
        </section>

    </header>

    <!-- Container -->
    <div class="content-wrap">
        @RenderBody()
    </div>
    <footer class="padding-50 dark ui-bg-color01"
            data-animation-origin="top"
            data-animation-duration="500"
            data-animation-delay="800"
            data-animation-distance="50px">
        <div class="container-fluid nopadding">
            <div class="row">
                <div class="col-md-12 copyrights">
                    <p>© 2017 Christina Wagner.</p>
                </div>
            </div>
        </div>
    </footer>
    <!-- Back to Top -->
    <div id="back-top"></div>
    <!-- /Back to Top -->
    <!-- JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script src="https://npmcdn.com/imagesloaded@4.1/imagesloaded.pkgd.min.js"></script>
    <script src="https://unpkg.com/isotope-layout@3.0/dist/isotope.pkgd.min.js"></script>
    <script src="https://unpkg.com/scrollreveal@3.3.2/dist/scrollreveal.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/velocity/1.2.3/velocity.min.js"></script>
    <script src="/wwwroot/assets/vendor/mfp/js/jquery.magnific-popup.min.js?v=1.1.0" type="text/javascript"></script>
    <script src="/wwwroot/assets/vendor/progressbar/progressbar.min.js?v=1.0.1" type="text/javascript"></script>
    <script src="/wwwroot/assets/vendor/anicounter/jquery.counterup.min.js?v=1.0" type="text/javascript"></script>
    @*<script src="/wwwroot/assets/vendor/pjax/jquery.pjax.min.js?v=1.9.6" type="text/javascript"></script>*@
    <script src="/wwwroot/assets/vendor/owl-carousel/owl.carousel.min.js?v=2.1.0" type="text/javascript"></script>
    <script src="/wwwroot/assets/vendor/headlines/headlines.min.js?v=1.0" type="text/javascript"></script>
    <!-- Custom scripts -->
    <script src="/wwwroot/assets/custom/2.2.0/js/animation.js" type="text/javascript"></script>
    @*<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAsWgr_mdf8Ur18wVezUR-SPIgorZPYEV8&callback=initGmap"
        type="text/javascript"></script>*@
    <script src="/wwwroot/assets/custom/2.2.0/js/custom.js" type="text/javascript"></script>
    <!--Syntax Highlighter-->
    <script src="~/Scripts/SyntaxHighlighter/shCore.js"></script>
    <script src="~/Scripts/SyntaxHighlighter/shBrushJScript.js"></script>
    @RenderSection("Scripts", false)

</body>
</html>