Controllers/PortfolioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using cwagnerPortfolio.Models;

namespace cwagnerPortfolio.Controllers
{
    [RequireHttps]
    public class PortfolioController : Controller
    {
        // GET: Portfolio
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult JS()
        {
            return View();
        }

        //COMMENTED OUT IN CASE THIS IS NEEDED AT A LATER TIME
        //public ActionResult ShoppingApp()
        //{
        //    return View();
        //}

        public ActionResult BugTracker()
        {
            return View();
        }

        public ActionResult FinancialPortal()
        {
            return View();
        }

        public PartialViewResult LoadJavascriptModal(JsExerciseViewModel model)
        {
            return PartialView("_JavascriptExerciseModal", model);
        }
    }
}

Controllers/ResumeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace cwagnerPortfolio.Controllers
{
    [RequireHttps]
    public class ResumeController : Controller
    {
        // GET: Resume
        public ActionResult Index()
        {
            return View();
        }
    }
}

Views/Resume/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div id="resume" class="inner-content">

    <section id="page-title" class="inner-section ui-menu-color02">
        <div class="container-fluid nopadding">
            <h2 class="font-accident-two-normal color01 uppercase"
                data-animation-origin="right"
                data-animation-duration="400"
                data-animation-delay="100"
                data-animation-distance="50px">
                Resume
            </h2>
            <h5 class="font-accident-two-bold color01 uppercase subtitle"
                data-animation-origin="right"
                data-animation-duration="400"
                data-animation-delay="200"
                data-animation-distance="50px"></h5>
            <p class="small color01"
               data-animation-origin="right"
               data-animation-duration="400"
               data-animation-delay="300"
               data-animation-distance="50px">
            </p>
        </div>
    </section>

    <!-- Timeline Block -->
    <section id="timeline" class="light inner-section">

        <div class="container-fluid nopadding">

            <div class="text-center"
                 data-animation-origin="top"
                 data-animation-duration="400"
                 data-animation-delay="400"
                 data-animation-distance="30px">
                <div class="dividewhite4"></div>
                <h3 class="font-accident-two-normal uppercase">Professional Timeline</h3>
                <h5 class="font-accident-two-bold uppercase subtitle">Working hard and making the success</h5>
                <div class="dividewhite1"></div>
                <p class="small fontcolor-medium">
                </p>
            </div>

            <div class="dividewhite4"></div>

            <ul class="timeline-vert timeline">
                <li>
                    <div class="timeline-badge primary"><i class="flaticon-graduation9"></i></div>
                    <div class="timeline-panel"
                         data-animation-origin="left"
                         data-animation-duration="400"
                         data-animation-delay="400"
                         data-animation-distance="25px">
                        <p class="timeline-time fontcolor-invert">Jul 2017 - Present</p>
                        <div class="timeline-photo timeline-helena-01"></div>
                        <div class="timeline-heading">
                            <h4 class="font-accident-two-normal uppercase">Coder Foundry, Kernersville, NC</h4>
                            <h6 class="uppercase">Student</h6>
                            <p>
                                18 week immersive full stack bootcamp
                            </p>
                        </div>
                    </div>
                </li>
                <li class="timeline-inverted">
                    <div class="timeline-badge success"><i class="flaticon-clocks18"></i></div>
                    <div class="timeline-panel"
                         data-animation-origin="right"
                         data-animation-duration="400"
                         data-animation-delay="400"
                         data-animation-distance="25px">
                        <p class="timeline-time fontcolor-invert">Jan 2016 - Jul 2017</p>
                        <div class="timeline-photo timeline-helena-02"></div>
                        <div class="timeline-heading">
                            <h4 class="font-accident-two-normal uppercase">Veterinary Specialty Hospital, Cary, NC</h4>
                            <h6 class="uppercase">Oncology Nurse II</h6>
                            <p>
                                Responsible for patient care including recording vital signs, appropriate lab work, and patient treatments.  Responsible for obtaining
                                accurate patient histories, complete medical records, and client education.  Essential skills include attention to detail, compassion,
                                customer service, work efficiency, teamwork and effective communication, and delegation of tasks to be completed.
                            </p>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="timeline-badge danger"><i class="flaticon-clocks18"></i></div>
                    <div class="timeline-panel"
                         data-animation-origin="left"
                         data-animation-duration="400"
                         data-animation-delay="400"
                         data-animation-distance="25px">
                        <p class="timeline-time fontcolor-invert">Aug 2009 - Jan 2016</p>
                        <div class="timeline-photo timeline-helena-03"></div>
                        <div class="timeline-heading">
                            <h4 class="font-accident-two-normal uppercase">Carolina Veterinary Specialists, Greensboro, NC</h4>
                            <h6 class="uppercase">Specialty Registered Veterinary Technician</h6>
                            <p>
                                Worked in Internal Medicine, Surgery, Oncology, Emergency, and Ophthalmology departments.  Responsible for obtaining accurate patient
                                histories, complete medical records, and client education.  Responsible for patient care including various lab and diagnostic testing,
                                medical treatments, and anesthesia.  Essential skills include attention to detail, compassion, customer service, work efficiency, teamwork,
                                and effective team communication.
                            </p>
                        </div>
                    </div>
                </li>
                <li class="timeline-inverted info">
                    <div class="timeline-badge warning"><i class="flaticon-graduation9"></i></div>
                    <div class="timeline-panel"
                         data-animation-origin="right"
                         data-animation-duration="400"
                         data-animation-delay="400"
                         data-animation-distance="25px">
                        <p class="timeline-time fontcolor-invert">Aug 2007 - Aug 2009</p>
                        <div class="timeline-photo timeline-helena-04"></div>
                        <div class="timeline-heading">
                            <h4 class="font-accident-two-normal uppercase">Central Carolina Community College, Sanford, NC</h4>
                            <h6 class="uppercase">AAS - Veterinary Medical Technology</h6>
                            <p>
                                Learning included a 3-month externship, which was completed at Carolina Veterinary Specialists in Greensboro, NC.
                            </p>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="timeline-badge danger"><i class="flaticon-graduation9"></i></div>
                    <div class="timeline-panel"
                         data-animation-origin="left"
                         data-animation-duration="400"
                         data-animation-delay="400"
                         data-animation-distance="25px">
                        <p class="timeline-time fontcolor-invert">Aug 2001 - May 2005</p>
                        <div class="timeline-photo timeline-helena-05"></div>
                        <div class="timeline-heading">
                            <h4 class="font-accident-two-normal uppercase">University of North Carolina at Wilmington</h4>
                            <h6 class="uppercase">BS - Marine Biology</h6>
                            <p>
                                Coursework included a semester abroad in Curacao, Netherlands Antilles studying coral reef ecosystems and coral reef research.
                            </p>
                        </div>
                    </div>
                </li>
            </ul>

            <div class="text-center">
                <a href="@Url.Action("Index", "Portfolio")" class="btn btn-darker"
                   data-animation-origin="bottom"
                   data-animation-duration="300"
                   data-animation-delay="600"
                   data-animation-distance="35px">View Portfolio</a>
            </div>

            <div class="dividewhite6"></div>
        </div>
    </section>
    <!-- /Timeline Block -->

</div>