Models/Blog.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace cwagnerPortfolio.Models
{
    public class Blog
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Slug { get; set; }
        [Required]
        [AllowHtml]
        public string Body { get; set; }
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset? Updated { get; set; }
        [Display(Name = "Image")]
        public string MediaUrl { get; set; }
        public bool Published { get; set; }

        public virtual ICollection<BlogComment>Comments { get; set; }

        public Blog()
        {
            Comments = new HashSet<BlogComment>();
        }
    }
}

Controllers/BlogCommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using cwagnerPortfolio.Models;
using Microsoft.AspNet.Identity;

namespace cwagnerPortfolio.Controllers
{
    public class BlogCommentController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: BlogComment
        //deleted

        // GET: BlogComment/Details/5
        //deleted

        // GET: BlogComment/Create
        //deleted

        // POST: BlogComment/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "Id,AuthorId,BlogId,Body,Created,Updated,UpdatedReason")] BlogComment blogComment, int blogId)
        {
            var blog = db.Posts.Find(blogId);

            if (ModelState.IsValid)
            {
                var user = db.Users.Find(User.Identity.GetUserId());

                blogComment.BlogId = blogId;
                blogComment.AuthorId = user.Id;
                blogComment.Created = DateTimeOffset.Now;
                db.BlogComments.Add(blogComment);
                db.SaveChanges();
            }

            return RedirectToAction("Details", "Blog", new { slug = blog.Slug });
        }

        // GET: BlogComment/Edit/5
        //deleted

        // POST: BlogComment/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(BlogComment updatedComment)
        {
            var blogComment = db.BlogComments.Find(updatedComment.Id);

            if (ModelState.IsValid && (User.IsInRole("Admin") || User.IsInRole("Moderator") || blogComment.AuthorId == User.Identity.GetUserId()))
            {
                blogComment.Updated = DateTimeOffset.Now;
                blogComment.Body = updatedComment.Body;
                
                db.Entry(blogComment).State = EntityState.Modified;
                db.SaveChanges();
            }

            return RedirectToAction("Details", "Blog", new { slug = blogComment.Blog.Slug });
        }

        // POST: BlogComment/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Delete(int id)
        {
            var blogComment = db.BlogComments.Find(id);

            if(User.IsInRole("Admin") || User.IsInRole("Moderator") || blogComment.AuthorId == User.Identity.GetUserId())
            {
            db.BlogComments.Remove(blogComment);
            db.SaveChanges();
            }

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using cwagnerPortfolio.Helpers;
using cwagnerPortfolio.Models;
using Microsoft.AspNet.Identity;
using PagedList;
using PagedList.Mvc;

namespace cwagnerPortfolio.Controllers
{
    [RequireHttps]
    public class BlogController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Blog
        public ActionResult Index(int? page)
        {
            int pageSize = 3;
            int pageNumber = (page ?? 1);

            var posts = db.Posts.OrderByDescending(d => d.Created).AsQueryable();

            if (!User.IsInRole("Admin")) posts = posts.Where(p => p.Published);

            return View(posts.Include(i => i.Comments).ToPagedList(pageNumber, pageSize));
        }

        // POST: Search
        [HttpPost]
        public ActionResult Index(string searchStr, int? page)
        {
            int pageSize = 3;
            int pageNumber = (page ?? 1);

            ViewBag.Search = searchStr;
            SearchHelper search = new SearchHelper();
            var blogList = search.IndexSearch(searchStr);

            if (Request.IsAuthenticated && User.IsInRole("Admin"))
            {
                return View(blogList.ToPagedList(pageNumber, pageSize));
            }
            else
            {
                return View(blogList.Where(p => p.Published == true).ToPagedList(pageNumber, pageSize));
            }
        }

        // GET: Blog/Details/5
        public ActionResult Details(string Slug)
        {
            if (String.IsNullOrWhiteSpace(Slug))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Posts.FirstOrDefault(p => p.Slug == Slug);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // GET: Blog/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            if (User.IsInRole("Admin"))
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        // POST: Blog/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "Id,Title,Slug,Body,Created,Updated,MediaUrl,Published")] Blog blog, HttpPostedFileBase image)
        {
            if (image != null && image.ContentLength > 0)
            {
                var ext = Path.GetExtension(image.FileName).ToLower();
                if (ext != ".png" && ext != ".jpg" && ext != ".jpeg" && ext != ".gif" && ext != ".bmp")
                    ModelState.AddModelError("image", "Invalid Format.");
            }
            if (ModelState.IsValid)
            {
                if(image != null)
                {
                    var filePath = "/wwwroot/images/";
                    var absPath = Server.MapPath("~" + filePath);
                    blog.MediaUrl = filePath + image.FileName;
                    image.SaveAs(Path.Combine(absPath, image.FileName));
                }
                var Slug = StringUtilities.URLFriendly(blog.Title);
                if (String.IsNullOrWhiteSpace(Slug))
                {
                    ModelState.AddModelError("Title", "Invalid title");
                    return View(blog);
                }
                if (db.Posts.Any(p => p.Slug == Slug))
                {
                    ModelState.AddModelError("Title", "The title must be unique");
                    return View(blog);
                }

                blog.Slug = Slug;
                blog.Created = DateTimeOffset.Now;
                db.Posts.Add(blog);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(blog);
        }

        // GET: Blog/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (User.IsInRole("Admin"))
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Blog blog = db.Posts.Find(id);
                if (blog == null)
                {
                    return HttpNotFound();
                }
                return View(blog);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        // POST: Blog/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "Id,Title,Slug,Body,Created,Updated,MediaUrl,Published")] Blog blog, string mediaURL, HttpPostedFileBase image)
        {
            if (image != null && image.ContentLength > 0)
            {
                var ext = Path.GetExtension(image.FileName).ToLower();
                if (ext != ".png" && ext != ".jpg" && ext != ".jpeg" && ext != ".gif" && ext != ".bmp")
                {
                    ModelState.AddModelError("image", "Invalid Format.");
                }
            }
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    var filePath = "/wwwroot/images/";
                    var absPath = Server.MapPath("~" + filePath);
                    blog.MediaUrl = filePath + image.FileName;
                    image.SaveAs(Path.Combine(absPath, image.FileName));
                }
                else
                {
                    blog.MediaUrl = mediaURL;
                }

                blog.Updated = DateTimeOffset.Now;
                db.Entry(blog).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blog);
        }

        // GET: Blog/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = db.Posts.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // POST: Blog/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Blog blog = db.Posts.Find(id);
            db.Posts.Remove(blog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Blog/Create.cshtml
@model cwagnerPortfolio.Models.Blog

@{
    ViewBag.Title = "Create";
}

<div id="blogpost" class="inner-content">

    <section class="inner-section feedback feedback-light" data-section="feedback">

        <div class="container-fluid nopadding">

            <div class="row">

                <div class=""
                     data-animation-origin="top"
                     data-animation-duration="500"
                     data-animation-delay="400"
                     data-animation-distance="25px">
                    <div class="dividewhite2"></div>
                    <h3 class="font-accident-two-normal uppercase text-center">Create blog post</h3>
                    <div class="dividewhite1"></div>
                </div>

                <div class="col-md-2">&nbsp;</div>
                <div class="col-md-8 e-centered"
                     data-animation-origin="top"
                     data-animation-duration="500"
                     data-animation-delay="600"
                     data-animation-distance="25px">
                    <div id="form-messages"></div>
                    @using (Html.BeginForm("Create", "Blog", FormMethod.Post,new { enctype = "Multipart/form-data" } ))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <hr />
                            <div class="wpcf7-form">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="field">
                                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-offset-0" })
                                    <input type="text" id="Title" name="Title" placeholder="Title" required>
                                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                                </div>

                                <div class="field">
                                    @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-offset-0" })
                                    <textarea id="Body" name="Body" placeholder="Body" rows="7" cols="30"></textarea>
                                    @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
                                </div>

                                <div class="field">
                                    @Html.LabelFor(model => model.MediaUrl, htmlAttributes: new { @class = "control-label col-md-offset-0" })
                                    <input type="file" id="MediaUrl" name="image" placeholder="MediaUrl" class="form-control">
                                    @Html.ValidationMessageFor(model => model.MediaUrl, "", new { @class = "text-danger" })
                                </div>

                                <div class="field">
                                    @Html.LabelFor(model => model.Published, htmlAttributes: new { @class = "col-md-offset-0 control-label" })
                                    <div class="pretty o-danger curvy a-tada">
                                        <input id="Published" name="Published" type="checkbox" value="true" @(Model?.Published == true ? "checked=\"checked\"" : "") />
                                        <label><i class="fa fa-check"></i></label>
                                    </div>
                                </div>

                                <div class="dividewhite2"></div>

                                <div class="field text-center">
                                    <button type="submit" class="btn btn-lg btn-darker">Save</button>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </section>
</div>
@section scripts{
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script src="~/Scripts/tinymce/jquery.tinymce.min.js"></script>
    <script type="text/javascript">
        $(function () {
            tinymce.init({
                selector: '#Body',
                plugins: "textcolor colorpicker emoticons link",
                toolbar: "forecolor backcolor emoticons link"
            });
        });
    </script>
}

Views/Blog/Delete.cshtml
@model cwagnerPortfolio.Models.Blog

@{
    ViewBag.Title = "Delete";
}

<div id="blogpost" class="inner-content">

    <section id="page-title" class="inner-section"
             data-animation-origin="right"
             data-animation-duration="500"
             data-animation-delay="300"
             data-animation-distance="25px">
        <div class="container-fluid nopadding">
            <h2 class="font-accident-two-normal uppercase">Delete Blog Entry</h2>
            <h4 class="font-accident-two-normal uppercase">Are you sure you want to delete this?</h4>
        </div>

        <div>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Title)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Title)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Slug)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Slug)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Body)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Body)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Created)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Created)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Updated)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Updated)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.MediaUrl)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.MediaUrl)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <div class="field text-center">
                        <button type="submit" class="btn btn-lg btn-darker">Delete</button>
                    </div>
                    @Html.ActionLink("Back to List", "Index")
                </div>
            }
        </div>
    </section>
</div>

Views/Blog/Details.cshtml
@model cwagnerPortfolio.Models.Blog
@using Microsoft.AspNet.Identity;

@{
    ViewBag.Title = Model.Title;
}

<div id="blogpost" class="inner-content">
    <form>
        @Html.AntiForgeryToken()
    </form>

    <section id="page-title" class="inner-section"
             data-animation-origin="right"
             data-animation-duration="500"
             data-animation-delay="300"
             data-animation-distance="25px">
        <div class="container-fluid nopadding">
            @Html.Partial("_LoginPartial")
            <h2 class="font-accident-two-normal uppercase">@Model.Title</h2>
            <div class="post-meta"><span>by <a>Christina</a>,</span> <span>@Model.Created.ToString("d")</span></div>
        </div>
    </section>

    <!-- Blog Block -->
    <section class="inner-section">

        <div class="container-fluid nopadding">

            <img src="@Model.MediaUrl" class="img-responsive"
                 alt=""
                 data-animation-origin="top"
                 data-animation-duration="500"
                 data-animation-delay="300"
                 data-animation-distance="25px">

            <article class="post"
                     data-animation-origin="top"
                     data-animation-duration="500"
                     data-animation-delay="300"
                     data-animation-distance="25px">

                <div class="dividewhite6"></div>

                <!-- Post Content -->
                @Html.Raw(Model.Body)
                <!-- /Post Content -->

                <div class="dividewhite4"></div>
                <p class="post-meta">
                    @if (User.IsInRole("Admin"))
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) <span> | </span>;
                        @Html.ActionLink("Delete", "Delete", new { id = Model.Id }) <span> | </span>;
                        @Html.ActionLink("Back to List", "Index");
                    }
                    else
                    {
                        @Html.ActionLink("Back to List", "Index");
                    }
                </p>
                <hr>

            </article>
        </div>
        <div class="dividewhite2"></div>
        <h3 class="font-accident-two-normal uppercase text-center">Comments</h3>
        <div class="col-md-12 e-centered"
             data-animation-origin="top"
             data-animation-duration="500"
             data-animation-delay="600"
             data-animation-distance="25px">
            <div id="form-messages"></div>
            <div class="dividewhite2"></div>
            @if (User.Identity.IsAuthenticated)
            {
                using (Html.BeginForm("Create", "BlogComment", new { blogId = Model.Id }, FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <div class="wpcf7-form">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="field">
                                <textarea type="text" id="Body" name="Body" placeholder="Leave a comment" rows="3" cols="30" required></textarea>
                            </div>
                            <div class="dividewhite2"></div>
                            <div class="field text-center">
                                <button type="submit" class="btn btn-lg btn-darker">Submit</button>
                                <div class="dividewhite2"></div>
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                <a href="@Url.Action("Login", "Account")">
                    <h5 class="font-accident-two-bold uppercase text-center subtitle">Login to leave a comment.</h5>
                </a>
                <div class="dividewhite2"></div>
            }
            @foreach (var item in Model.Comments)
            {
                <div class="row" data-id="@item.Id">
                    <article id="01" class="post-block col-sm-12 post hentry"
                             data-animation-origin="top"
                             data-animation-duration="500"
                             data-animation-delay="500"
                             data-animation-distance="30px">
                        <div id="comment-body-@item.Id">
                            <p>@item.Body</p>
                        </div>
                        <div id="editForm-@item.Id" style="display:none;" >
                            @using (Html.BeginForm("Edit", "BlogComment", new { blogId = Model.Id }, FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()
                                @Html.Hidden("Id", item.Id)

                                <div class="form-horizontal">
                                    <div class="wpcf7-form">
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        <div class="field">
                                            <textarea type="text" id="Body" name="Body" placeholder="Leave a comment" rows="3" cols="30" required>@item.Body</textarea>
                                        </div>
                                        <div class="dividewhite2"></div>
                                        <div class="field text-center">
                                            <button onclick="toggleCommentEdit(@item.Id)" type="button" class="btn btn-lg btn-light">Cancel</button>
                                            <button type="submit" class="btn btn-lg btn-darker">Submit</button>
                                            <div class="dividewhite2"></div>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                        <div class="post-meta">
                            Posted on: <a class="meta-date">@item.Created.ToString("d")</a>&nbsp;
                            Posted by: <a class="meta-author">@item.Author.FullName</a>&nbsp;
                            <div>
                                @if (User.IsInRole("Admin") || User.IsInRole("Moderator") || item.AuthorId == User.Identity.GetUserId())
                                {
                                    <a href="javascript:void(0)" onclick="toggleCommentEdit(@item.Id)">Edit</a> <span> | </span>;
                                    <a href="javascript:void(0)" onclick="commentDelete(@item.Id, '@Url.Action("Delete", "BlogComment", new { id = item.Id }, null)')">Delete</a>;
                                }
                            </div>
                        </div>
                        <hr />
                    </article>
                </div>
            }
        </div>


    </section>
    <!-- /Blog Block -->
</div>
@section scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.9.1/sweetalert2.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.9.1/sweetalert2.css" />
    <link href="~/wwwroot/assets/custom/2.2.0/css/sweetAlert.css" rel="stylesheet" />
    <script src="~/wwwroot/assets/custom/2.2.0/js/deleteComment.js"></script>
}

Views/Blog/Edit.cshtml
@model cwagnerPortfolio.Models.Blog

@{
    ViewBag.Title = "Edit";
}

<div id="blogpost" class="inner-content">

    <section class="inner-section feedback feedback-light" data-section="feedback">

        <div class="container-fluid nopadding">

            <div class="row">

                <div class=""
                     data-animation-origin="top"
                     data-animation-duration="500"
                     data-animation-delay="400"
                     data-animation-distance="25px">
                    <div class="dividewhite2"></div>
                    <h3 class="font-accident-two-normal uppercase text-center">Edit blog post</h3>
                    <div class="dividewhite1"></div>
                </div>

                <div class="col-md-2">&nbsp;</div>
                <div class="col-md-8 e-centered"
                     data-animation-origin="top"
                     data-animation-duration="500"
                     data-animation-delay="600"
                     data-animation-distance="25px">
                    <div id="form-messages"></div>
                    @using (Html.BeginForm("Edit", "Blog", new { mediaUrl = Model.MediaUrl }, FormMethod.Post, new { enctype = "Multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <hr />
                            <div class="wpcf7-form">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.Id)
                                @Html.HiddenFor(model => model.Slug)
                                @Html.HiddenFor(model => model.Created)
                                @Html.HiddenFor(model => model.Updated)

                                <div class="field">
                                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-offset-0" })
                                    <input type="text" id="Title" name="Title" placeholder="Title" value="@Model.Title" required>
                                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                                </div>

                                <div class="field">
                                    @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-offset-0" })
                                    <textarea id="Body" name="Body" placeholder="Body" rows="7" cols="30">@Model.Body</textarea>
                                    @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
                                </div>

                                <div class="field">
                                    @Html.LabelFor(model => model.MediaUrl, htmlAttributes: new { @class = "control-label col-md-offset-0" })
                                    <input type="file" id="MediaUrl" name="image" placeholder="MediaUrl" value="@Model.MediaUrl" class="form-control">
                                    @Html.ValidationMessageFor(model => model.MediaUrl, "", new { @class = "text-danger" })
                                </div>

                                <div class="field">
                                    @Html.LabelFor(model => model.Published, htmlAttributes: new { @class = "col-md-offset-0 control-label" })
                                    <div class="pretty o-danger curvy a-tada">
                                        <input id="Published" name="Published" type="checkbox" value="true" @(Model.Published == true ? "checked=\"checked\"" : "") />
                                        <label><i class="fa fa-check"></i></label>
                                    </div>
                                </div>

                                <div class="dividewhite2"></div>

                                <div class="field text-center">
                                    <button type="submit" class="btn btn-lg btn-darker">Save</button>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </section>
</div>
@section scripts{
<script src="~/Scripts/tinymce/tinymce.min.js"></script>
<script src="~/Scripts/tinymce/jquery.tinymce.min.js"></script>
<script type="text/javascript">
    $(function () {
        tinymce.init({
            selector: '#Body',
            plugins: "textcolor colorpicker emoticons link",
            toolbar: "forecolor backcolor emoticons link"
        });
    });
</script>

}